name: Foo

on:
  workflow_dispatch:
    input:
      environment:
        type: choice
          description: Environment to deploy to
          options:
          - uat
          - prod
          required: true
        

jobs:
  foo: 
    runs-on: ubuntu-latest

    steps:
    - name: Echo
      run: echo "Deploying to environment '${{ github.event.inputs.environment }}"