name: Release

on:
  release:
    types: [published]

jobs:
  job1:
    name: Create release artifacts 
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        id: setup
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo $VERSION
          echo ::set-output name=version::$VERSION

      - name: Mock build
        run: echo "Building release ${{steps.setup.output.version}}"

      - name: Mock push
        run: echo "Pushing release artifacts"
