name: Prod - Sync Develop w/ Main

on:
  push:
    branches:
      - main

jobs:
  Sync: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: develop
          fetch-depth: 0
          # token: ${{ secrets.GH_TOKEN }}


      - name: Merge main into develop
        run: |
          git config user.name "Marge"
          git fetch origin main:main
          git merge main
          git push